version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: iot_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
